// <auto-generated />
using AJStudio.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AJStudio.Data.Migrations
{
    [DbContext(typeof(AJStudioContext))]
    partial class AJStudioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AJStudio.Data.DBTables.ContactUsDBTable", b =>
                {
                    b.Property<long>("Customer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Customer_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Customer_Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("City");

                    b.Property<string>("Customer_Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Customer_Comment");

                    b.Property<string>("Customer_Selected_Plane")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Customer_Selected_Plane");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("First_Name");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Last_Name");

                    b.Property<string>("Mobile_Number")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mobile_Number");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("State");

                    b.Property<string>("Suggested")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Suggested");

                    b.HasKey("Customer_Id");

                    b.ToTable("ContactUsTable");
                });

            modelBuilder.Entity("AJStudio.Data.DBTables.PlaneVarietyDBTable", b =>
                {
                    b.Property<long>("PlaneVariety_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PlaneVariety_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlaneVariety_Id"));

                    b.Property<string>("PlaneVariety")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PlaneVariety");

                    b.HasKey("PlaneVariety_Id");

                    b.ToTable("PlaneVarietyTable");
                });

            modelBuilder.Entity("AJStudio.Data.DBTables.SuggestedDBTable", b =>
                {
                    b.Property<long>("Suggested_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Suggested_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Suggested_Id"));

                    b.Property<string>("Suggested")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Suggested");

                    b.HasKey("Suggested_Id");

                    b.ToTable("SuggestedTable");
                });
#pragma warning restore 612, 618
        }
    }
}
